//
//  Service.swift
//  5words10seconds
//
//  Created by Heorhii Savoiskyi on 30.10.2023.
//

import Foundation

struct Service {
    static let shared = Service()

    private var level: Int?

    private init() {}

    func chooseLevel(integet _: Int) { // todo level of categories
    }

    func getLevel() -> Int? { // very much to do
        return level
    }

    func fetchTeams(_ completion: @escaping (Result<Set<TeamModel>, Error>) -> Void) {
        switch SetupViewModel().currentLanguage.value {
        case "uk":
            completion(.success(allTeamsUa))
        default:
            completion(.success(allTeamsEng))
        }
    }

    func fetchCategories(_ completion: @escaping (Result<[CategorySwiftModel], Error>) -> Void) {
        switch SetupViewModel().currentLanguage.value {
        case "uk":
            completion(.success(categoriesTMPUa))
        default:
            completion(.success(categoriesTMPEng))
        }
    }

//     useless things from exmaple:
//    static func fetchGameLevels(_ completion: @escaping (Result<[GameLevelModel], Error>) -> ()) {
//        completion(.success(gameLevels))
//    }
}

// let gameLevels: [GameLevelModel] = []

let allTeamsEng: Set = [
    // TeamModel(name: "Tomatoes", score: 0),
    // TeamModel(name: "Sleepwalkers", score: 0),
    // TeamModel(name: "Penguins", score: 0),
    // TeamModel(name: "Pineapples", score: 0),
    // TeamModel(name: "Pirates", score: 0),
    // TeamModel(name: "Angels", score: 0),
    TeamModel(name: "Incredible Impalas", score: 0),
    TeamModel(name: "Optimistic Ocelots", score: 0),
    TeamModel(name: "Flaming Flamingos", score: 0),
    TeamModel(name: "Joyful Jaguars", score: 0),
    TeamModel(name: "Shining Sharks", score: 0),
    TeamModel(name: "Talented Tarantulas", score: 0),
    TeamModel(name: "Unique Unicorns", score: 0),
    TeamModel(name: "Fantastic Foxes", score: 0),
    TeamModel(name: "Brave Butterflies", score: 0),
    TeamModel(name: "Curious Cheetahs", score: 0),
    TeamModel(name: "Magical Moths", score: 0),
    TeamModel(name: "Crazy Coyotes", score: 0),
    TeamModel(name: "Happy Hyenas", score: 0),
    TeamModel(name: "Young Yetis", score: 0),
    TeamModel(name: "Bright Beavers", score: 0),
    TeamModel(name: "Golden Geckos", score: 0),
    TeamModel(name: "Intellectual Iguanas", score: 0),
    TeamModel(name: "Creative Crabs", score: 0),
    TeamModel(name: "Legendary Lemurs", score: 0),
    TeamModel(name: "Wise Walruses", score: 0),
    TeamModel(name: "Adventurous Antelopes", score: 0),
    TeamModel(name: "Bubbly Bees", score: 0),
    TeamModel(name: "Clever Chameleons", score: 0),
    TeamModel(name: "Daring Dolphins", score: 0),
    TeamModel(name: "Energetic Elephants", score: 0),
    TeamModel(name: "Funny Frogs", score: 0),
    TeamModel(name: "Glowing Giraffes", score: 0),
    TeamModel(name: "Happy Hippos", score: 0),
    TeamModel(name: "Inventive Ibises", score: 0),
    TeamModel(name: "Joyful Jackals", score: 0),
    TeamModel(name: "Kind Kangaroos", score: 0),
    TeamModel(name: "Lively Lions", score: 0),
    TeamModel(name: "Merry Meerkats", score: 0),
    TeamModel(name: "Nimble Newts", score: 0),
    TeamModel(name: "Optimistic Otters", score: 0),
    TeamModel(name: "Playful Penguins", score: 0),
    TeamModel(name: "Quick Quails", score: 0),
    TeamModel(name: "Radiant Rabbits", score: 0),
    TeamModel(name: "Spirited Squirrels", score: 0),
    TeamModel(name: "Thrilling Tigers", score: 0),
]

let allTeamsUa: Set = [
    //    TeamModel(name: "Помідори", score: 0),
//    TeamModel(name: "Сомнамбули", score: 0),
//    TeamModel(name: "Пінгвіни", score: 0),
//    TeamModel(name: "Ананаси", score: 0),
//    TeamModel(name: "Пірати", score: 0),
//    TeamModel(name: "Янголи", score: 0),
//    TeamModel(name: "Коти", score: 0),
//    TeamModel(name: "Собаки", score: 0),
//    TeamModel(name: "Кролики", score: 0),
    TeamModel(name: "Блискучі Буряки", score: 0),
    TeamModel(name: "Веселі Вітрули", score: 0),
    TeamModel(name: "Галасливі Горішки", score: 0),
    TeamModel(name: "Дивовижні Динозаври", score: 0),
    TeamModel(name: "Єдиналітні Єноти", score: 0),
    TeamModel(name: "Запальні Зірки", score: 0),
    TeamModel(name: "Іскристі Індики", score: 0),
    TeamModel(name: "Крихітні Комети", score: 0),
    TeamModel(name: "Лунатичні Ліхтарі", score: 0),
    TeamModel(name: "Міцні Метеорити", score: 0),
    TeamModel(name: "Незламні Небожителі", score: 0),
    TeamModel(name: "Оптимістичні Орли", score: 0),
    TeamModel(name: "Полум'яні Персонажі", score: 0),
    TeamModel(name: "Радісні Ракети", score: 0),
    TeamModel(name: "Сяйливі Суперзірки", score: 0),
    TeamModel(name: "Талановиті Титани", score: 0),
    TeamModel(name: "Унікальні Уфологи", score: 0),
    TeamModel(name: "Фантастичні Феї", score: 0),
    TeamModel(name: "Хоробрі Химери", score: 0),
    TeamModel(name: "Цікаві Циклони", score: 0),
    TeamModel(name: "Чарівні Чаклуни", score: 0),
    TeamModel(name: "Шалені Шамани", score: 0),
    TeamModel(name: "Щасливі Щурі", score: 0),
    TeamModel(name: "Юні Юпітеряни", score: 0),
    TeamModel(name: "Яскраві Янголи", score: 0),
    TeamModel(name: "Неймовірні Німфи", score: 0),
    TeamModel(name: "Оптимістичні Октопуси", score: 0),
    TeamModel(name: "Полум'яні Піонери", score: 0),
    TeamModel(name: "Радісні Роботи", score: 0),
    TeamModel(name: "Сяйливі Супутники", score: 0),
    TeamModel(name: "Талановиті Торнадо", score: 0),
    TeamModel(name: "Унікальні Утопісти", score: 0),
    TeamModel(name: "Фантастичні Футуристи", score: 0),
    TeamModel(name: "Хоробрі Художники", score: 0),
    TeamModel(name: "Цікаві Циркачі", score: 0),
    TeamModel(name: "Чарівні Чародії", score: 0),
    TeamModel(name: "Шалені Шахраї", score: 0),
    TeamModel(name: "Щасливі Щури", score: 0),
    TeamModel(name: "Юні Юнголи", score: 0),
    TeamModel(name: "Яскраві Ястреби", score: 0),
    TeamModel(name: "Золоті Зорепади", score: 0),
    TeamModel(name: "Інтелектуальні Індіанці", score: 0),
    TeamModel(name: "Креативні Космонавти", score: 0),
    TeamModel(name: "Легендарні Леви", score: 0),
    TeamModel(name: "Мудрі Музиканти", score: 0),
]

let categoriesTMPEng: [CategorySwiftModel] = [
    CategorySwiftModel(name: "European countries", level: 0, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Bad Habits", level: 0, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Green fruits and vagetables", level: 0, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Colors", level: 0, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Superheroes", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Anime Series", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Computer Games", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Music Bands", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Fashion Brands", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Types of Dances", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Historical Events", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Famous Inventions", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Space Objects", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Mythical Creatures", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Famous Places of the World", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Famous Places of Europe", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Famous Places of Asia", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Famous Places of America", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Famous Places of Africa", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Famous Places of Australia", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Types of Sports", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Types of Art", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Types of Science", level: 5, language: SupportedLanguages.english.rawValue),
]

let categoriesTMPUa: [CategorySwiftModel] = [
//    CategoryModel(name: "Європейські країни", level: 0),
//    CategoryModel(name: "Погані звички", level: 0),
//    CategoryModel(name: "Зелені фрукти та овочі", level: 0),
//    CategoryModel(name: "Кольори", level: 0),
//    CategoryModel(name: "Живі організми в океані", level: 0),
//    CategoryModel(name: "Види спорту", level: 0),
//    CategoryModel(name: "Музичні інструменти", level: 0),
//    CategoryModel(name: "Знамениті письменники", level: 0),
//    CategoryModel(name: "Елементи автомобіля", level: 0),
//    CategoryModel(name: "Види танців", level: 0),
//    CategoryModel(name: "Космічні об'єкти", level: 0),
//    CategoryModel(name: "Живі організми в джунглях", level: 0),
//    CategoryModel(name: "Види тканин", level: 0),
//    CategoryModel(name: "Знамениті актори", level: 0),
//    CategoryModel(name: "Елементи комп'ютера", level: 0),
//    CategoryModel(name: "Види меблів", level: 0),
//    CategoryModel(name: "Живі організми в пустелі", level: 0),
//    CategoryModel(name: "Види музики", level: 0),
//    CategoryModel(name: "Знамениті спортсмени", level: 0),
//    CategoryModel(name: "Елементи будинку", level: 0),
]

let challengingCategoriesUa: [CategorySwiftModel] = [
//    CategoryModel(name: "Формули в хімії", level: 10),
//    CategoryModel(name: "Теорії в фізиці", level: 10),
//    CategoryModel(name: "Види програмування", level: 10),
//    CategoryModel(name: "Історичні події", level: 10),
//    CategoryModel(name: "Види хмар", level: 10),
//    CategoryModel(name: "Види математичних рівнянь", level: 10),
//    CategoryModel(name: "Види алгоритмів", level: 10),
//    CategoryModel(name: "Види архітектури", level: 10),
//    CategoryModel(name: "Види музичних жанрів", level: 10),
//    CategoryModel(name: "Види художніх стилів", level: 10),
//    CategoryModel(name: "Види філософій", level: 10),
//    CategoryModel(name: "Види психологічних теорій", level: 10),
//    CategoryModel(name: "Види економічних систем", level: 10),
//    CategoryModel(name: "Види політичних систем", level: 10),
//    CategoryModel(name: "Види правових систем", level: 10),
//    CategoryModel(name: "Види медичних спеціальностей", level: 10),
//    CategoryModel(name: "Види біологічних класифікацій", level: 10),
//    CategoryModel(name: "Види геологічних форм", level: 10),
//    CategoryModel(name: "Види астрономічних об'єктів", level: 10),
//    CategoryModel(name: "Види літературних жанрів", level: 10),
]

let diverseCategoriesUa: [CategorySwiftModel] = [
    // CategoryModel(name: "Космічні програми", level: 5),
    // CategoryModel(name: "Музичні інструменти", level: 5),
    // CategoryModel(name: "Кулінарні страви", level: 5),
    // CategoryModel(name: "Спортивне спорядження", level: 5),
    // CategoryModel(name: "Тварини Африки", level: 5),
    // CategoryModel(name: "Тварини Австралії", level: 5),
    // CategoryModel(name: "Тварини Азії", level: 5),
    // CategoryModel(name: "Тварини Америки", level: 5),
    // CategoryModel(name: "Фільми про подорожі", level: 5),
    // CategoryModel(name: "Книги про пригоди", level: 5),
    // CategoryModel(name: "Відомі художники", level: 5),
    // CategoryModel(name: "Відомі композитори", level: 5),
    // CategoryModel(name: "Відомі письменники", level: 5),
    // CategoryModel(name: "Відомі вчені", level: 5),
    // CategoryModel(name: "Відомі спортсмени", level: 5),
    // CategoryModel(name: "Відомі актори", level: 5),
    // CategoryModel(name: "Відомі режисери", level: 5),
    // CategoryModel(name: "Відомі музиканти", level: 5),
    // CategoryModel(name: "Відомі політики", level: 5),
    // CategoryModel(name: "Міста України", level: 5),
    // CategoryModel(name: "Міста Європи", level: 5),
    // CategoryModel(name: "Міста Азії", level: 5),
    // CategoryModel(name: "Міста Америки", level: 5),
    // CategoryModel(name: "Міста Африки", level: 5),
    // CategoryModel(name: "Міста Австралії", level: 5),
    // CategoryModel(name: "Видатні будівлі світу", level: 5),
    // CategoryModel(name: "Видатні мости світу", level: 5),
    // CategoryModel(name: "Видатні парки світу", level: 5),
    // CategoryModel(name: "Супергерої", level: 5),
    // CategoryModel(name: "Аніме серіали", level: 5),
    // CategoryModel(name: "Комп'ютерні ігри", level: 5),
    // CategoryModel(name: "Музичні гурти", level: 5),
    // CategoryModel(name: "Модні бренди", level: 5),
    // CategoryModel(name: "Види танців", level: 5),
    // CategoryModel(name: "Історичні події", level: 5),
    // CategoryModel(name: "Відомі винаходи", level: 5),
    // CategoryModel(name: "Космічні об'єкти", level: 5),
    CategorySwiftModel(name: "Міфічні істоти", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    
    CategorySwiftModel(name: "Квіти", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Рослини", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Частини тіла", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Предмети посуду", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Домашні страви", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Геометричні фігури", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Предмети для роботи в городі", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Предмети для походу", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Двозначні числа", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Речі, які можна можна побачити в небі", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Водоймища", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Позитивні риси характеру", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Планети", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Кондитерські вироби", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Головні убори", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Родичі", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Речі, що можна знайти на дні моря", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Тропічні фрукти", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Одиниці вимірювання", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Риби", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Свята", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Меблі", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Предмети для прибирання", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Молочні продукти", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Тварини, що живуть на фермі", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Домашні тварини", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Предмети одягу", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Напої", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Алкогольні напої", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Емоції", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Міста України", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Штати США", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Казкові герої", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Овочі", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Фрукти", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Ягоди", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Птахи", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Марки автомобілів", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Зачіски", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Місяці року", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Предмети на літеру «Р»", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Предмети на літеру «С»", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Рухливих ігор", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Видів транспорту", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Олімпійські види спорту", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Зимові олімпійські види спорту", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Великі тварин", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Явища природи", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Ягоди червоного кольору", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Прикраси", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Предметів з ящику для інструментів", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Мови", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Країни світу", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Види спорту де не використовують мʼяч", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Спортивні бренди", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Птахи які можна побачити в зимку", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Солодкі речі", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Найкращий подарунок для вас", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Місця, де може бути дзеркало", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Чоловічі імена на літеру «С»", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Жіночі імена на літеру «К»", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Казкових принцес", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Настільні ігри", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Компʼютерні ігри", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Назви книжок", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Письменники", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Предмети, якими можна малювати", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Іграшки", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Світові моря", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Спортивні ігри з мʼячем", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Смаки морозива", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Хижі тварини", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Кухонні пристрої", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Живі істоти з крилами", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Аксесуари для вбрання", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Види побутової техніки", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Народи світу", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Тварини з копитами", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Рослини що ростуть на городі", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Чисел на літерну Д", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Електронні прилади, які використовуються щодня ", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Жовті фрукти", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Кислі продукти", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Вулиці Вашого міста", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Страви, які зазвичай їдять на сніданок", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Речі з вашої кімнати", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Тварини з хвостом", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Рептилії", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Тварини які ви бачили в зоопарку", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Горіхи", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Музичні інструменти з струнами", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Пристрої для прослуховування музики", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Дитячі пісні", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Приголосні літери", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Страви, які вживають холодними", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Герої мультфільмів", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Зелені предмети", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Страви, які вживають гарячими", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Тварини, що вміють плавати", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Міфічні істоти", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Комахи, які літають", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Види випічки", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Страви на святковому столі", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Супергерої", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Дорогоцінні камені", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Предмети для школи", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Професії", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Університети України", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Університети Світу", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Чоловічі імена на літеру «О»", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Жіночі імена на літеру «Н»", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Мультики", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Памʼятки світу", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Дива світу", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Магазини", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Овочі, що ростуть в землі", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Породи собак", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Породи котів", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Вироби з тіста", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Домашні тварини", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Види риб", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Види з родини котячих", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Види жіночого взуття", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Торгівельні центри", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Весняні свята", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Засоби для прибирання в будигнку", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Міста, які популярні серед туристів", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Види косметики, для догляду за шкірою", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Національності", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Приводи подарувати комусь квіти", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Тварини які мешкають в Україні", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Соціальні мережі", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Світові бренди", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Кухонні інструменти", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Негативні риси характеру", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Способи дістатись до школи", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Страви після яких хочеться пити", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Слова на англійській мові", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Комедії", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Професії, повʼязані зі здоровʼям", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Персонажі з класичної літератури", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Ознаки Різдва", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Дитячі хвороби", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Найпопулярніші тварини з мультиків", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Види кави", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Види чаю", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Речі, які люди найчастіше забувають сказати", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Фільми жахів", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Гори", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Книги з дитиною в головній ролі", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Відтінки синього кольору", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Комахи, які не літають", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Пристрої, для звукозапису", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Професії, повʼязані з фізичною працею", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Місця, які Ви хочете відвідати", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Види транспорту, які пересуваються тільки по маршруту", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Професії повʼязані з ремонтом", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Овочі зеленого кольору", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Історичні особливості з імʼям Олена", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Види сиру", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Слова на букву «Е»", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Страви, які не прийнято їсти в обід", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Професії в селі", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Отруйні рослини", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Отруйні тварини", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Актори", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Ягоди які ростуть в лісі", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Елементи таблиці Менделєєва", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Письменники Золотого століття", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Імена які закінчуються на «лав»", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Державні свята", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Предмети старовини, якими й досі користуються", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Історичні фільми", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Асоціації до слова «Експерт»", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Предмети які не можна прати", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Країни, які омиває океан", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Корисні звички", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Пʼєси", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Фільми про новий рік", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Види делікатесів", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Види екзотичних фруктів", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Страви азіатської кухні", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Страви з риби", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Ознаки випускника", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Види молока", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Країни Європи", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Речі, які найчастіше роблять на новий рік", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Хімічні явища", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Причини жити в селі", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Страви з курки", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Популярні клички для котів", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Популярні клички для собак", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Види спортивного бою", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Одиниці виміру ваги", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Види спорту", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Види головних уборів", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Рими до слова «правда»", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Музиканти", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Музичні гурти", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Слова, що означають вітання", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Види комах що мешкають в місті", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Річки", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Країни на букву «К»", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Історичні епохи", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Рослини які можна вирощувать на балконі", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Продукти, які входять до складу котлет", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Слова, що позначають прощання", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Приводи, щоб випити чай", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Квіти, які бувають червоного кольору", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Документи, які потрібні при влаштуванні на роботу", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Страви з картоплі", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Світові релігії", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Речі, які є в приватному будинку", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Цитати з реклами TV", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Пісні з реклами TV", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Марки цукерок", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Філософи", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Письменники-філософи", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Марки цукерок", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Види їстівної «трави»", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Види активного відпочинку", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Речі, які хочеш робити але не можеш", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Відомі відьми", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Квіти, які бувають білого кольору", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Продукти харчування, які вважаються гарнірами", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Види будівельних матеріалів", level: 5, language: SupportedLanguages.ukrainian.rawValue),
    CategorySwiftModel(name: "Речі, які люди роблять на роботі", level: 5, language: SupportedLanguages.ukrainian.rawValue),
]

let diverseCategoriesEn: [CategorySwiftModel] = [
    CategorySwiftModel(name: "Flowers", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Plants", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Body parts", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Dishware items", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Homemade dishes", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Geometric shapes", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Gardening tools", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Hiking gear", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Two-digit numbers", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Things you can see in the sky", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Bodies of water", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Positive character traits", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Planets", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Confectionery products", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Headwear", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Relatives", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Things you can find at the bottom of the sea", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Tropical fruits", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Units of measurement", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Fish", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Holidays", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Furniture", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Cleaning supplies", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Dairy products", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Farm animals", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Pets", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Clothing items", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Drinks", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Alcoholic beverages", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Emotions", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Cities of Ukraine", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "States of the USA", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Fairy tale characters", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Vegetables", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Fruits", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Berries", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Birds", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Car brands", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Hairstyles", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Months of the year", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Items starting with the letter \"R\"", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Items starting with the letter \"S\"", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Active games", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Types of transport", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Olympic sports", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Winter Olympic sports", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Large animals", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Natural phenomena", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Red berries", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Jewelry", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Items from a toolbox", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Languages", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Countries of the world", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Sports without a ball", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Sport brands", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Birds you can see in winter", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Sweet things", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "The best gift for you", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Places where you can find a mirror", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Male names starting with \"S\"", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Female names starting with \"K\"", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Fairy tale princesses", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Board games", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Computer games", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Book titles", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Writers", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Items you can draw with", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Toys", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "World's seas", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Sports games with a ball", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Ice cream flavors", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Predatory animals", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Kitchen appliances", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Living creatures with wings", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Clothing accessories", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Types of household appliances", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Peoples of the world", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Hoofed animals", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Garden plants", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Numbers starting with \"D\"", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Everyday electronic devices", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Yellow fruits", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Sour products", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Streets of your city", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Typical breakfast dishes", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Items from your room", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Animals with tails", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Reptiles", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Animals you've seen in a zoo", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Nuts", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "String musical instruments", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Devices for listening to music", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Children's songs", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Consonant letters", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Dishes usually eaten cold", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Cartoon characters", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Green items", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Dishes usually eaten hot", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Animals that can swim", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Mythical creatures", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Flying insects", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Types of pastries", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Holiday table dishes", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Superheroes", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Precious stones", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "School supplies", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Professions", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Universities of Ukraine", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "World's universities", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Male names starting with \"O\"", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Female names starting with \"N\"", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Cartoons", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "World landmarks", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Wonders of the world", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Stores", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Vegetables that grow underground", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Dog breeds", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Cat breeds", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Pastry products", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Pets", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Types of fish", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Types of cats", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Types of women's shoes", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Shopping malls", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Spring holidays", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Cleaning tools", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Cities popular among tourists", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Types of skincare cosmetics", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Nationalities", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Reasons to give someone flowers", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Animals living in Ukraine", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Social networks", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "World brands", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Kitchen tools", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Negative character traits", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Ways to get to school", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Dishes that make you thirsty", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "English words", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Comedies", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Health-related professions", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Characters from classic literature", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Signs of Christmas", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Children's diseases", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Most popular animals from cartoons", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Types of coffee", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Types of tea", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Things people often forget to say", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Horror movies", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Mountains", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Books with a child in the main role", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Shades of blue", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Insects that don't fly", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Sound recording devices", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Physically demanding professions", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Places you want to visit", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Types of transport that only move along a route", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Repair-related professions", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Green vegetables", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Historical figures named Olena", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Types of cheese", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Words starting with \"E\"", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Dishes not usually eaten for lunch", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Village professions", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Poisonous plants", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Poisonous animals", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Actors", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Berries that grow in the forest", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Elements of the periodic table", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Writers of the Golden Age", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Names ending with \"lav\"", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Public holidays", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Antique items still in use", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Historical movies", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Associations with the word \"Expert\"", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Items that can't be washed", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Countries bordered by an ocean", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Healthy habits", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Plays", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "New Year's movies", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Types of delicacies", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Exotic fruits", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Asian cuisine dishes", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Fish dishes", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Signs of a graduate", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Types of milk", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Countries of Europe", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Things people usually do on New Year's", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Chemical phenomena", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Reasons to live in a village", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Chicken dishes", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Popular cat names", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Popular dog names", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Types of combat sports", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Units of weight measurement", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Types of sports", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Types of headwear", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Rhymes with the word \"truth\"", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Musicians", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Music bands", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Words that mean greeting", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Types of city-dwelling insects", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Rivers", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Countries starting with \"K\"", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Historical epochs", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Plants you can grow on a balcony", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Ingredients for cutlets", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Words that mean farewell", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Reasons to have tea", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Flowers that are red", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Documents needed for a job", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Potato dishes", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "World religions", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Things in a private house", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Quotes from TV ads", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Songs from TV ads", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Candy brands", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Philosophers", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Philosopher writers", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Candy brands", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Types of edible \"grass\"", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Types of active rest", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Things you want to do but can't", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Famous witches", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Flowers that are white", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Food items considered side dishes", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Types of building materials", level: 5, language: SupportedLanguages.english.rawValue),
    CategorySwiftModel(name: "Things people do at work", level: 5, language: SupportedLanguages.english.rawValue),
]
