//
//  Service.swift
//  5words10seconds
//
//  Created by Heorhii Savoiskyi on 30.10.2023.
//

import Foundation

struct Service {
    static let shared = Service()

    private var level: Int?

    private init() {}

    func chooseLevel(integet _: Int) { // todo level of categories
    }

    func getLevel() -> Int? { // very much to do
        return level
    }

    func fetchTeams(_ completion: @escaping (Result<Set<TeamModel>, Error>) -> Void) {
        switch MenuViewModel().currentLanguage.value {
        case "uk":
            completion(.success(allTeamsUa))
        default:
            completion(.success(allTeamsEng))
        }
    }

    func fetchCategories(_ completion: @escaping (Result<[CategoryModel], Error>) -> Void) {
        switch MenuViewModel().currentLanguage.value {
        case "uk":
            completion(.success(categoriesTMPUa))
        default:
            completion(.success(categoriesTMPEng))
        }
    }

//     useless things from exmaple:
//    static func fetchGameLevels(_ completion: @escaping (Result<[GameLevelModel], Error>) -> ()) {
//        completion(.success(gameLevels))
//    }
}

// let gameLevels: [GameLevelModel] = []

let allTeamsEng: Set = [
    // TeamModel(name: "Tomatoes", score: 0),
    // TeamModel(name: "Sleepwalkers", score: 0),
    // TeamModel(name: "Penguins", score: 0),
    // TeamModel(name: "Pineapples", score: 0),
    // TeamModel(name: "Pirates", score: 0),
    // TeamModel(name: "Angels", score: 0),
    TeamModel(name: "Incredible Impalas", score: 0),
    TeamModel(name: "Optimistic Ocelots", score: 0),
    TeamModel(name: "Flaming Flamingos", score: 0),
    TeamModel(name: "Joyful Jaguars", score: 0),
    TeamModel(name: "Shining Sharks", score: 0),
    TeamModel(name: "Talented Tarantulas", score: 0),
    TeamModel(name: "Unique Unicorns", score: 0),
    TeamModel(name: "Fantastic Foxes", score: 0),
    TeamModel(name: "Brave Butterflies", score: 0),
    TeamModel(name: "Curious Cheetahs", score: 0),
    TeamModel(name: "Magical Moths", score: 0),
    TeamModel(name: "Crazy Coyotes", score: 0),
    TeamModel(name: "Happy Hyenas", score: 0),
    TeamModel(name: "Young Yetis", score: 0),
    TeamModel(name: "Bright Beavers", score: 0),
    TeamModel(name: "Golden Geckos", score: 0),
    TeamModel(name: "Intellectual Iguanas", score: 0),
    TeamModel(name: "Creative Crabs", score: 0),
    TeamModel(name: "Legendary Lemurs", score: 0),
    TeamModel(name: "Wise Walruses", score: 0),
    TeamModel(name: "Adventurous Antelopes", score: 0),
    TeamModel(name: "Bubbly Bees", score: 0),
    TeamModel(name: "Clever Chameleons", score: 0),
    TeamModel(name: "Daring Dolphins", score: 0),
    TeamModel(name: "Energetic Elephants", score: 0),
    TeamModel(name: "Funny Frogs", score: 0),
    TeamModel(name: "Glowing Giraffes", score: 0),
    TeamModel(name: "Happy Hippos", score: 0),
    TeamModel(name: "Inventive Ibises", score: 0),
    TeamModel(name: "Joyful Jackals", score: 0),
    TeamModel(name: "Kind Kangaroos", score: 0),
    TeamModel(name: "Lively Lions", score: 0),
    TeamModel(name: "Merry Meerkats", score: 0),
    TeamModel(name: "Nimble Newts", score: 0),
    TeamModel(name: "Optimistic Otters", score: 0),
    TeamModel(name: "Playful Penguins", score: 0),
    TeamModel(name: "Quick Quails", score: 0),
    TeamModel(name: "Radiant Rabbits", score: 0),
    TeamModel(name: "Spirited Squirrels", score: 0),
    TeamModel(name: "Thrilling Tigers", score: 0),
]

let allTeamsUa: Set = [
    //    TeamModel(name: "Помідори", score: 0),
//    TeamModel(name: "Сомнамбули", score: 0),
//    TeamModel(name: "Пінгвіни", score: 0),
//    TeamModel(name: "Ананаси", score: 0),
//    TeamModel(name: "Пірати", score: 0),
//    TeamModel(name: "Янголи", score: 0),
//    TeamModel(name: "Коти", score: 0),
//    TeamModel(name: "Собаки", score: 0),
//    TeamModel(name: "Кролики", score: 0),
    TeamModel(name: "Блискучі Буряки", score: 0),
    TeamModel(name: "Веселі Вітрули", score: 0),
    TeamModel(name: "Галасливі Горішки", score: 0),
    TeamModel(name: "Дивовижні Динозаври", score: 0),
    TeamModel(name: "Єдиналітні Єноти", score: 0),
    TeamModel(name: "Запальні Зірки", score: 0),
    TeamModel(name: "Іскристі Індики", score: 0),
    TeamModel(name: "Крихітні Комети", score: 0),
    TeamModel(name: "Лунатичні Ліхтарі", score: 0),
    TeamModel(name: "Міцні Метеорити", score: 0),
    TeamModel(name: "Незламні Небожителі", score: 0),
    TeamModel(name: "Оптимістичні Орли", score: 0),
    TeamModel(name: "Полум'яні Персонажі", score: 0),
    TeamModel(name: "Радісні Ракети", score: 0),
    TeamModel(name: "Сяйливі Суперзірки", score: 0),
    TeamModel(name: "Талановиті Титани", score: 0),
    TeamModel(name: "Унікальні Уфологи", score: 0),
    TeamModel(name: "Фантастичні Феї", score: 0),
    TeamModel(name: "Хоробрі Химери", score: 0),
    TeamModel(name: "Цікаві Циклони", score: 0),
    TeamModel(name: "Чарівні Чаклуни", score: 0),
    TeamModel(name: "Шалені Шамани", score: 0),
    TeamModel(name: "Щасливі Щурі", score: 0),
    TeamModel(name: "Юні Юпітеряни", score: 0),
    TeamModel(name: "Яскраві Янголи", score: 0),
    TeamModel(name: "Неймовірні Німфи", score: 0),
    TeamModel(name: "Оптимістичні Октопуси", score: 0),
    TeamModel(name: "Полум'яні Піонери", score: 0),
    TeamModel(name: "Радісні Роботи", score: 0),
    TeamModel(name: "Сяйливі Супутники", score: 0),
    TeamModel(name: "Талановиті Торнадо", score: 0),
    TeamModel(name: "Унікальні Утопісти", score: 0),
    TeamModel(name: "Фантастичні Футуристи", score: 0),
    TeamModel(name: "Хоробрі Художники", score: 0),
    TeamModel(name: "Цікаві Циркачі", score: 0),
    TeamModel(name: "Чарівні Чародії", score: 0),
    TeamModel(name: "Шалені Шахраї", score: 0),
    TeamModel(name: "Щасливі Щури", score: 0),
    TeamModel(name: "Юні Юнголи", score: 0),
    TeamModel(name: "Яскраві Ястреби", score: 0),
    TeamModel(name: "Золоті Зорепади", score: 0),
    TeamModel(name: "Інтелектуальні Індіанці", score: 0),
    TeamModel(name: "Креативні Космонавти", score: 0),
    TeamModel(name: "Легендарні Леви", score: 0),
    TeamModel(name: "Мудрі Музиканти", score: 0),
]

let categoriesTMPEng: [CategoryModel] = [
    CategoryModel(name: "European countries", level: 0),
    CategoryModel(name: "Bad Habits", level: 0),
    CategoryModel(name: "Green fruits and vagetables", level: 0),
    CategoryModel(name: "Colors", level: 0),
    CategoryModel(name: "Superheroes", level: 5),
    CategoryModel(name: "Anime Series", level: 5),
    CategoryModel(name: "Computer Games", level: 5),
    CategoryModel(name: "Music Bands", level: 5),
    CategoryModel(name: "Fashion Brands", level: 5),
    CategoryModel(name: "Types of Dances", level: 5),
    CategoryModel(name: "Historical Events", level: 5),
    CategoryModel(name: "Famous Inventions", level: 5),
    CategoryModel(name: "Space Objects", level: 5),
    CategoryModel(name: "Mythical Creatures", level: 5),
    CategoryModel(name: "Famous Places of the World", level: 5),
    CategoryModel(name: "Famous Places of Europe", level: 5),
    CategoryModel(name: "Famous Places of Asia", level: 5),
    CategoryModel(name: "Famous Places of America", level: 5),
    CategoryModel(name: "Famous Places of Africa", level: 5),
    CategoryModel(name: "Famous Places of Australia", level: 5),
    CategoryModel(name: "Types of Sports", level: 5),
    CategoryModel(name: "Types of Art", level: 5),
    CategoryModel(name: "Types of Science", level: 5),
]

let categoriesTMPUa: [CategoryModel] = [
    CategoryModel(name: "Європейські країни", level: 0),
    CategoryModel(name: "Погані звички", level: 0),
    CategoryModel(name: "Зелені фрукти та овочі", level: 0),
    CategoryModel(name: "Кольори", level: 0),
    CategoryModel(name: "Живі організми в океані", level: 0),
    CategoryModel(name: "Види спорту", level: 0),
    CategoryModel(name: "Музичні інструменти", level: 0),
    CategoryModel(name: "Знамениті письменники", level: 0),
    CategoryModel(name: "Елементи автомобіля", level: 0),
    CategoryModel(name: "Види танців", level: 0),
    CategoryModel(name: "Космічні об'єкти", level: 0),
    CategoryModel(name: "Живі організми в джунглях", level: 0),
    CategoryModel(name: "Види тканин", level: 0),
    CategoryModel(name: "Знамениті актори", level: 0),
    CategoryModel(name: "Елементи комп'ютера", level: 0),
    CategoryModel(name: "Види меблів", level: 0),
    CategoryModel(name: "Живі організми в пустелі", level: 0),
    CategoryModel(name: "Види музики", level: 0),
    CategoryModel(name: "Знамениті спортсмени", level: 0),
    CategoryModel(name: "Елементи будинку", level: 0),
]

let challengingCategoriesUa: [CategoryModel] = [
    CategoryModel(name: "Формули в хімії", level: 10),
    CategoryModel(name: "Теорії в фізиці", level: 10),
    CategoryModel(name: "Види програмування", level: 10),
    CategoryModel(name: "Історичні події", level: 10),
    CategoryModel(name: "Види хмар", level: 10),
    CategoryModel(name: "Види математичних рівнянь", level: 10),
    CategoryModel(name: "Види алгоритмів", level: 10),
    CategoryModel(name: "Види архітектури", level: 10),
    CategoryModel(name: "Види музичних жанрів", level: 10),
    CategoryModel(name: "Види художніх стилів", level: 10),
    CategoryModel(name: "Види філософій", level: 10),
    CategoryModel(name: "Види психологічних теорій", level: 10),
    CategoryModel(name: "Види економічних систем", level: 10),
    CategoryModel(name: "Види політичних систем", level: 10),
    CategoryModel(name: "Види правових систем", level: 10),
    CategoryModel(name: "Види медичних спеціальностей", level: 10),
    CategoryModel(name: "Види біологічних класифікацій", level: 10),
    CategoryModel(name: "Види геологічних форм", level: 10),
    CategoryModel(name: "Види астрономічних об'єктів", level: 10),
    CategoryModel(name: "Види літературних жанрів", level: 10),
]

let diverseCategoriesUa: [CategoryModel] = [
    // CategoryModel(name: "Транспорт", level: 5),
    // CategoryModel(name: "Космічні програми", level: 5),
    // CategoryModel(name: "Музичні інструменти", level: 5),
    // CategoryModel(name: "Кулінарні страви", level: 5),
    // CategoryModel(name: "Спортивне спорядження", level: 5),
    // CategoryModel(name: "Тварини Африки", level: 5),
    // CategoryModel(name: "Тварини Австралії", level: 5),
    // CategoryModel(name: "Тварини Азії", level: 5),
    // CategoryModel(name: "Тварини Америки", level: 5),
    // CategoryModel(name: "Фільми про подорожі", level: 5),
    // CategoryModel(name: "Книги про пригоди", level: 5),
    // CategoryModel(name: "Відомі художники", level: 5),
    // CategoryModel(name: "Відомі композитори", level: 5),
    // CategoryModel(name: "Відомі письменники", level: 5),
    // CategoryModel(name: "Відомі вчені", level: 5),
    // CategoryModel(name: "Відомі спортсмени", level: 5),
    // CategoryModel(name: "Відомі актори", level: 5),
    // CategoryModel(name: "Відомі режисери", level: 5),
    // CategoryModel(name: "Відомі музиканти", level: 5),
    // CategoryModel(name: "Відомі політики", level: 5),
    // CategoryModel(name: "Міста України", level: 5),
    // CategoryModel(name: "Міста Європи", level: 5),
    // CategoryModel(name: "Міста Азії", level: 5),
    // CategoryModel(name: "Міста Америки", level: 5),
    // CategoryModel(name: "Міста Африки", level: 5),
    // CategoryModel(name: "Міста Австралії", level: 5),
    // CategoryModel(name: "Видатні будівлі світу", level: 5),
    // CategoryModel(name: "Видатні мости світу", level: 5),
    // CategoryModel(name: "Видатні парки світу", level: 5),
    // CategoryModel(name: "Супергерої", level: 5),
    // CategoryModel(name: "Аніме серіали", level: 5),
    // CategoryModel(name: "Комп'ютерні ігри", level: 5),
    // CategoryModel(name: "Музичні гурти", level: 5),
    // CategoryModel(name: "Модні бренди", level: 5),
    // CategoryModel(name: "Види танців", level: 5),
    // CategoryModel(name: "Історичні події", level: 5),
    // CategoryModel(name: "Відомі винаходи", level: 5),
    // CategoryModel(name: "Космічні об'єкти", level: 5),
    // CategoryModel(name: "Міфічні істоти", level: 5),
    CategoryModel(name: "Квіти", level: 5),
    CategoryModel(name: "Рослини", level: 5),
    CategoryModel(name: "Частини тіла", level: 5),
    CategoryModel(name: "Предмети посуду", level: 5),
    CategoryModel(name: "Домашні страви", level: 5),
    CategoryModel(name: "Геометричні фігури", level: 5),
    CategoryModel(name: "Предмети для роботи в городі", level: 5),
    CategoryModel(name: "Предмети для походу", level: 5),
    CategoryModel(name: "Двозначні числа", level: 5),
    CategoryModel(name: "Речі, які можна можна побачити в небі", level: 5),
    CategoryModel(name: "Водоймища", level: 5),
    CategoryModel(name: "Позитивні риси характеру", level: 5),
    CategoryModel(name: "Планети", level: 5),
    CategoryModel(name: "Кондитерські вироби", level: 5),
    CategoryModel(name: "Головні убори", level: 5),
    CategoryModel(name: "Родичі", level: 5),
    CategoryModel(name: "Речі, що можна знайти на дні моря", level: 5),
    CategoryModel(name: "Тропічні фрукти", level: 5),
    CategoryModel(name: "Одиниці вимірювання", level: 5),
    CategoryModel(name: "Риби", level: 5),
    CategoryModel(name: "Свята", level: 5),
    CategoryModel(name: "Меблі", level: 5),
    CategoryModel(name: "Предмети для прибирання", level: 5),
    CategoryModel(name: "Молочні продукти", level: 5),
    CategoryModel(name: "Тварини, що живуть на фермі", level: 5),
    CategoryModel(name: "Домашні тварини", level: 5),
    CategoryModel(name: "Предмети одягу", level: 5),
    CategoryModel(name: "Напої", level: 5),
    CategoryModel(name: "Алкогольні напої", level: 5),
    CategoryModel(name: "Емоції", level: 5),
    CategoryModel(name: "Міста України", level: 5),
    CategoryModel(name: "Штати США", level: 5),
    CategoryModel(name: "Казкові герої", level: 5),
    CategoryModel(name: "Овочі", level: 5),
    CategoryModel(name: "Фрукти", level: 5),
    CategoryModel(name: "Ягоди", level: 5),
    CategoryModel(name: "Птахи", level: 5),
    CategoryModel(name: "Марки автомобілів", level: 5),
    CategoryModel(name: "Зачіски", level: 5),
    CategoryModel(name: "Місяці року", level: 5),
    CategoryModel(name: "Предмети на літеру «Р»", level: 5),
    CategoryModel(name: "Предмети на літеру «С»", level: 5),
    CategoryModel(name: "Рухливих ігор", level: 5),
    CategoryModel(name: "Видів транспорту", level: 5),
    CategoryModel(name: "Олімпійські види спорту", level: 5),
    CategoryModel(name: "Зимові олімпійські види спорту", level: 5),
    CategoryModel(name: "Великі тварин", level: 5),
    CategoryModel(name: "Явища природи", level: 5),
    CategoryModel(name: "Ягоди червоного кольору", level: 5),
    CategoryModel(name: "Прикраси", level: 5),
    CategoryModel(name: "Предметів з ящику для інструментів", level: 5),
    CategoryModel(name: "Мови", level: 5),
    CategoryModel(name: "Країни світу", level: 5),
    CategoryModel(name: "Види спорту де не використовують мʼяч", level: 5),
    CategoryModel(name: "Спортивні бренди", level: 5),
    CategoryModel(name: "Птахи які можна побачити в зимку", level: 5),
    CategoryModel(name: "Солодкі речі", level: 5),
    CategoryModel(name: "Найкращий подарунок для вас", level: 5),
    CategoryModel(name: "Місця, де може бути дзеркало", level: 5),
    CategoryModel(name: "Чоловічі імена на літеру «С»", level: 5),
    CategoryModel(name: "Жіночі імена на літеру «К»", level: 5),
    CategoryModel(name: "Казкових принцес", level: 5),
    CategoryModel(name: "Настільні ігри", level: 5),
    CategoryModel(name: "Компʼютерні ігри", level: 5),
    CategoryModel(name: "Назви книжок", level: 5),
    CategoryModel(name: "Письменники", level: 5),
    CategoryModel(name: "Предмети, якими можна малювати", level: 5),
    CategoryModel(name: "Іграшки", level: 5),
    CategoryModel(name: "Світові моря", level: 5),
    CategoryModel(name: "Спортивні ігри з мʼячем", level: 5),
    CategoryModel(name: "Смаки морозива", level: 5),
    CategoryModel(name: "Хижі тварини", level: 5),
    CategoryModel(name: "Кухонні пристрої", level: 5),
    CategoryModel(name: "Живі істоти з крилами", level: 5),
    CategoryModel(name: "Аксесуари для вбрання", level: 5),
    CategoryModel(name: "Види побутової техніки", level: 5),
    CategoryModel(name: "Народи світу", level: 5),
    CategoryModel(name: "Тварини з копитами", level: 5),
    CategoryModel(name: "Рослини що ростуть на городі", level: 5),
    CategoryModel(name: "Чисел на літерну Д", level: 5),
    CategoryModel(name: "Електронні прилади, які використовуються щодня ", level: 5),
    CategoryModel(name: "Жовті фрукти", level: 5),
    CategoryModel(name: "Кислі продукти", level: 5),
    CategoryModel(name: "Вулиці Вашого міста", level: 5),
    CategoryModel(name: "Страви, які зазвичай їдять на сніданок", level: 5),
    CategoryModel(name: "Речі з вашої кімнати", level: 5),
    CategoryModel(name: "Тварини з хвостом", level: 5),
    CategoryModel(name: "Рептилії", level: 5),
    CategoryModel(name: "Тварини які ви бачили в зоопарку", level: 5),
    CategoryModel(name: "Горіхи", level: 5),
    CategoryModel(name: "Музичні інструменти з струнами", level: 5),
    CategoryModel(name: "Пристрої для прослуховування музики", level: 5),
    CategoryModel(name: "Дитячі пісні", level: 5),
    CategoryModel(name: "Приголосні літери", level: 5),
    CategoryModel(name: "Страви, які вживають холодними", level: 5),
    CategoryModel(name: "Герої мультфільмів", level: 5),
    CategoryModel(name: "Зелені предмети", level: 5),
    CategoryModel(name: "Страви, які вживають гарячими", level: 5),
    CategoryModel(name: "Тварини, що вміють плавати", level: 5),
    CategoryModel(name: "Міфічні істоти", level: 5),
    CategoryModel(name: "Комахи, які літають", level: 5),
    CategoryModel(name: "Види випічки", level: 5),
    CategoryModel(name: "Страви на святковому столі", level: 5),
    CategoryModel(name: "Супергерої", level: 5),
    CategoryModel(name: "Дорогоцінні камені", level: 5),
    CategoryModel(name: "Предмети для школи", level: 5),
    CategoryModel(name: "Професії", level: 5),
    CategoryModel(name: "Університети України", level: 5),
    CategoryModel(name: "Університети Світу", level: 5),
    CategoryModel(name: "Чоловічі імена на літеру «О»", level: 5),
    CategoryModel(name: "Жіночі імена на літеру «Н»", level: 5),
    CategoryModel(name: "Мультики", level: 5),
    CategoryModel(name: "Памʼятки світу", level: 5),
    CategoryModel(name: "Дива світу", level: 5),
    CategoryModel(name: "Магазини", level: 5),
    CategoryModel(name: "Овочі, що ростуть в землі", level: 5),
    CategoryModel(name: "Породи собак", level: 5),
    CategoryModel(name: "Породи котів", level: 5),
    CategoryModel(name: "Вироби з тіста", level: 5),
    CategoryModel(name: "Домашні тварини", level: 5),
    CategoryModel(name: "Види риб", level: 5),
    CategoryModel(name: "Види з родини котячих", level: 5),
    CategoryModel(name: "Види жіночого взуття", level: 5),
    CategoryModel(name: "Торгівельні центри", level: 5),
    CategoryModel(name: "Весняні свята", level: 5),
    CategoryModel(name: "Засоби для прибирання в будигнку", level: 5),
    CategoryModel(name: "Міста, які популярні серед туристів", level: 5),
    CategoryModel(name: "Види косметики, для догляду за шкірою", level: 5),
    CategoryModel(name: "Національності", level: 5),
    CategoryModel(name: "Приводи подарувати комусь квіти", level: 5),
    CategoryModel(name: "Тварини які мешкають в Україні", level: 5),
    CategoryModel(name: "Соціальні мережі", level: 5),
    CategoryModel(name: "Світові бренди", level: 5),
    CategoryModel(name: "Кухонні інструменти", level: 5),
    CategoryModel(name: "Негативні риси характеру", level: 5),
    CategoryModel(name: "Способи дістатись до школи", level: 5),
    CategoryModel(name: "Страви після яких хочеться пити", level: 5),
    CategoryModel(name: "Слова на англійській мові", level: 5),
    CategoryModel(name: "Комедії", level: 5),
    CategoryModel(name: "Професії, повʼязані зі здоровʼям", level: 5),
    CategoryModel(name: "Персонажі з класичної літератури", level: 5),
    CategoryModel(name: "Ознаки Різдва", level: 5),
    CategoryModel(name: "Дитячі хвороби", level: 5),
    CategoryModel(name: "Найпопулярніші тварини з мультиків", level: 5),
    CategoryModel(name: "Види кави", level: 5),
    CategoryModel(name: "Види чаю", level: 5),
    CategoryModel(name: "Речі, які люди найчастіше забувають сказати", level: 5),
    CategoryModel(name: "Фільми жахів", level: 5),
    CategoryModel(name: "Гори", level: 5),
    CategoryModel(name: "Книги з дитиною в головній ролі", level: 5),
    CategoryModel(name: "Відтінки синього кольору", level: 5),
    CategoryModel(name: "Комахи, які не літають", level: 5),
    CategoryModel(name: "Пристрої, для звукозапису", level: 5),
    CategoryModel(name: "Професії, повʼязані з фізичною працею", level: 5),
    CategoryModel(name: "Місця, які Ви хочете відвідати", level: 5),
    CategoryModel(name: "Види транспорту, які пересуваються тільки по маршруту", level: 5),
    CategoryModel(name: "Професії повʼязані з ремонтом", level: 5),
    CategoryModel(name: "Овочі зеленого кольору", level: 5),
    CategoryModel(name: "Історичні особливості з імʼям Олена", level: 5),
    CategoryModel(name: "Види сиру", level: 5),
    CategoryModel(name: "Слова на букву «Е»", level: 5),
    CategoryModel(name: "Страви, які не прийнято їсти в обід", level: 5),
    CategoryModel(name: "Професії в селі", level: 5),
    CategoryModel(name: "Отруйні рослини", level: 5),
    CategoryModel(name: "Отруйні тварини", level: 5),
    CategoryModel(name: "Актори", level: 5),
    CategoryModel(name: "Ягоди які ростуть в лісі", level: 5),
    CategoryModel(name: "Елементи таблиці Менделєєва", level: 5),
    CategoryModel(name: "Письменники Золотого століття", level: 5),
    CategoryModel(name: "Імена які закінчуються на «лав»", level: 5),
    CategoryModel(name: "Державні свята", level: 5),
    CategoryModel(name: "Предмети старовини, якими й досі користуються", level: 5),
    CategoryModel(name: "Історичні фільми", level: 5),
    CategoryModel(name: "Асоціації до слова «Експерт»", level: 5),
    CategoryModel(name: "Предмети які не можна прати", level: 5),
    CategoryModel(name: "Країни, які омиває океан", level: 5),
    CategoryModel(name: "Корисні звички", level: 5),
    CategoryModel(name: "Пʼєси", level: 5),
    CategoryModel(name: "Фільми про новий рік", level: 5),
    CategoryModel(name: "Види делікатесів", level: 5),
    CategoryModel(name: "Види екзотичних фруктів", level: 5),
    CategoryModel(name: "Страви азіатської кухні", level: 5),
    CategoryModel(name: "Страви з риби", level: 5),
    CategoryModel(name: "Ознаки випускника", level: 5),
    CategoryModel(name: "Види молока", level: 5),
    CategoryModel(name: "Країни Європи", level: 5),
    CategoryModel(name: "Речі, які найчастіше роблять на новий рік", level: 5),
    CategoryModel(name: "Хімічні явища", level: 5),
    CategoryModel(name: "Причини жити в селі", level: 5),
    CategoryModel(name: "Страви з курки", level: 5),
    CategoryModel(name: "Популярні клички для котів", level: 5),
    CategoryModel(name: "Популярні клички для собак", level: 5),
    CategoryModel(name: "Види спортивного бою", level: 5),
    CategoryModel(name: "Одиниці виміру ваги", level: 5),
    CategoryModel(name: "Види спорту", level: 5),
    CategoryModel(name: "Види головних уборів", level: 5),
    CategoryModel(name: "Рими до слова «правда»", level: 5),
    CategoryModel(name: "Музиканти", level: 5),
    CategoryModel(name: "Музичні гурти", level: 5),
    CategoryModel(name: "Слова, що означають вітання", level: 5),
    CategoryModel(name: "Види комах що мешкають в місті", level: 5),
    CategoryModel(name: "Річки", level: 5),
    CategoryModel(name: "Країни на букву «К»", level: 5),
    CategoryModel(name: "Історичні епохи", level: 5),
    CategoryModel(name: "Рослини які можна вирощувать на балконі", level: 5),
    CategoryModel(name: "Продукти, які входять до складу котлет", level: 5),
    CategoryModel(name: "Слова, що позначають прощання", level: 5),
    CategoryModel(name: "Приводи, щоб випити чай", level: 5),
    CategoryModel(name: "Квіти, які бувають червоного кольору", level: 5),
    CategoryModel(name: "Документи, які потрібні при влаштуванні на роботу", level: 5),
    CategoryModel(name: "Страви з картоплі", level: 5),
    CategoryModel(name: "Світові релігії", level: 5),
    CategoryModel(name: "Речі, які є в приватному будинку", level: 5),
    CategoryModel(name: "Цитати з реклами TV", level: 5),
    CategoryModel(name: "Пісні з реклами TV", level: 5),
    CategoryModel(name: "Марки цукерок", level: 5),
    CategoryModel(name: "Філософи", level: 5),
    CategoryModel(name: "Письменники-філософи", level: 5),
    CategoryModel(name: "Марки цукерок", level: 5),
    CategoryModel(name: "Види їстівної «трави»", level: 5),
    CategoryModel(name: "Види активного відпочинку", level: 5),
    CategoryModel(name: "Речі, які хочеш робити але не можеш", level: 5),
    CategoryModel(name: "Відомі відьми", level: 5),
    CategoryModel(name: "Квіти, які бувають білого кольору", level: 5),
    CategoryModel(name: "Продукти харчування, які вважаються гарнірами", level: 5),
    CategoryModel(name: "Види будівельних матеріалів", level: 5),
    CategoryModel(name: "Речі, які люди роблять на роботі", level: 5),
]
